version: "3.9"

services:
  redis:
    image: redis:7.2.4-alpine3.19
    hostname: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: >
      --include /usr/local/etc/redis/redis.conf
    volumes:
      - "/src/core/configs/data:/root/redis"
      - "/src/core/configs/redis.conf:/usr/local/etc/redis/redis.conf"

  supplyfy-chatbot:
    image: ignaichatbotassets.azurecr.io/supplyfy-chatbot:latest
    hostname: supplyfy-chatbot
    container_name: supplyfy-chatbot
    restart: always
    depends_on:
      - redis
    ports:
     - "8000:8000"