version: "3.9"

services:
  redis:
    image: redis:latest
    hostname: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: >
      --include /usr/local/etc/redis/redis.conf
    volumes:
      - "/home/thomasafg/Documentos/diamondbigger/supplyfy-chatbot/src/core/configs/data:/root/redis"
      - "/home/thomasafg/Documentos/diamondbigger/supplyfy-chatbot/src/core/configs/redis.conf:/usr/local/etc/redis/redis.conf"
    networks:
      - mynetwork

  chatbot:
    build: 
      context: .
      args:
        ENV: ${ENV}
    hostname: chatbot
    container_name: chatbot
    restart: always
    depends_on:
      - redis
    ports:
     - "8000:8000"
    env_file:
      - .env
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
    # external:
    #   name: test-kafka-local_default