version: "3.9"

services:
  redis:
    image: ignaichatbotassets.azurecr.io/redis:latest
    hostname: redis
    container_name: redis
    restart: always
    environment:
      WEBSITES_ENABLE_APP_SERVICE_STORAGE: TRUE
    networks:
      - redis_network
      
  supplyfy-chatbot:
    image: ignaichatbotassets.azurecr.io/supplyfy-chatbot:latest
    hostname: supplyfy-chatbot
    container_name: supplyfy-chatbot
    restart: always
    depends_on:
      - redis
    ports:
     - "80:8000"
    networks:
      - redis_network

networks:
    redis_network: