version: "3.9"

services:
  redis:
    build: ./redis
    hostname: redis
    container_name: redis
    restart: always
    privileged: true
    environment:
      WEBSITES_ENABLE_APP_SERVICE_STORAGE: TRUE
    networks:
      - redis_network
      
  supplyfy-chatbot:
    build: .
    hostname: supplyfy-chatbot
    container_name: supplyfy-chatbot
    restart: always
    depends_on:
      - redis
    ports:
     - "80:8000"
    networks:
      - redis_network

networks:
    redis_network: