version: "3.9"

services:
  redis:
    image: ignaichatbotassets.azurecr.io/redis:latest
    hostname: redis
    container_name: redis
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"
      
  supplyfy-chatbot:
    image: ignaichatbotassets.azurecr.io/supplyfy-chatbot:latest
    hostname: supplyfy-chatbot
    container_name: supplyfy-chatbot
    ports:
     - "80:8000"
