export const MAIN_WATERFALL_DIALOG = 'MAIN_WATERFALL_DIALOG';

export const WATERFALL_DIALOG = 'WATERFALL_DIALOG';

export const USER_PROFILE_PROPERTY = 'USER_PROFILE_PROPERTY';

export const MAIN_DIALOG = 'MAIN_DIALOG';

export const CONVERSATION_DIALOG = 'CONVERSATION_DIALOG';

export const CHAT_DIALOG = 'CHAT_DIALOG';

export const WELCOMED_USER = 'WELCOMED_USER';

export const CONVERSATION_DATA_PROPERTY = 'CONVERSATION_DATA_PROPERTY';